### PR TITLE
Refactored for Python 3.4

### PR DESCRIPTION
**Pull request by SaileshPatel**
Refactored the code for Python 3.4, but due to the lack of 'xrange' there is an error, where all the ascii codes are singular instead of in rows.

### CODE REVIEW

**Comment by notexactlyawe** [comment]
I made your code compatible with python2 again, but I have no easy way of testing it on 3, could you check for me?

**Comment by SaileshPatel** [comment]
It's not working
I've attached the error message below:

screenshot 2015-10-28 18 55 56

**Comment by notexactlyawe** [comment]
Cheers, I've just pushed a change which should hopefully fix that

**Comment by SaileshPatel** [comment]
It works 
The end result! 

koala

**Pull request merged**
